# NT Traitors
- type: entity
  parent: BaseMindRoleAntag
  id: MindRoleTraitorNT
  name: Traitor Role (NanoTrasen)
  components:
  - type: MindRole
    antagPrototype: TraitorNT
    exclusiveAntag: true
    subtype: role-subtype-traitor
  - type: TraitorRole

- type: entity
  parent: MindRoleTraitor
  id: MindRoleTraitorSleeperNT
  name: Sleeper Agent Role (NanoTrasen)
  components:
  - type: MindRole
    antagPrototype: TraitorSleeperNT

- type: entity
  parent: MindRoleTraitor
  id: MindRoleTraitorReinforcementNT
  name: NanoTrasen Reinforcement Role
  components:
  - type: MindRole
    roleType: TeamAntagonist
    subtype: role-subtype-traitor-reinforcement
    antagPrototype: GenericTeamAntagonist
